tasks:
  - name: Setup
    init: > 
        pip install aider-chat
    #docker-compose up &&
    #gp sync-done initSetup
    command: gp open README.md && ls
  
    #command: gp open README.md && gp open CrewAi.ipynb && marimo edit hello-world-marimo.py

  #- name: Marimo
  #  init: gp sync-await initSetup # wait for the above defined 'initSetup' to finish
  #  command: marimo edit hello-world-marimo.py
  #  openMode: split-right

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers